apiVersion: redhatgov.io/v1alpha1
kind: PloigosPlatform
metadata:
  name: ploigosplatform
spec:
  ploigosPlatform:
    #helmRepository: https://ploigos.github.io/ploigos-charts
    services:
      continuousIntegration:
        tekton:
          enabled: true
      sourceControl:
        gitea:
          enabled: true
      artifactRepository:
        nexusArtifacts:
          enabled: true
      staticCodeAnalysis:
        sonarqube:
          enabled: true
      continuousDeployment:
        argocd:
          enabled: true
      uat:
        selenium:
          enabled: true
      containerRegistry:
        nexusContainers:
          enabled: true
